### PR TITLE
docs: tweak faq

### PR DESCRIPTION
**Pull request by killme2008**
## What's Changed in this PR

As the title said.

## Checklist

- [ ] Please ensure that the content in `summary.yml` matches the current document structure when you changed the document structure.
- [ ] This change requires follow-up update in localized docs.

### CODE REVIEW

**Comment by killme2008** [comment]
Looks like the FAQ and release note are still missing in greptime.cn @nicecui @tisonkun 

If we don't have time to translate them, just use the english version is good.

**Comment by killme2008** [comment]
@nicecui @fengjiachun Every time a new version is release, we can't just only add new documents for them, but also have to update old documents with wrong informations.

**Comment by nicecui** [comment]
please add `FAQ-and-Others: 常见问题及其他` to summary-i18n.yml, thank you very much!

**Comment by nicecui** [comment]
@GreptimeTeam/marketing Please remember to update the content in the marketing internal documentation.

**Comment by nicecui** [comment]
> @nicecui @fengjiachun Every time a new version is released, we can't just only add new documents for them, but also have to update old documents with outdated information.

yes, It should be

**Review by tisonkun — APPROVED** [review]

**Review by nicecui — APPROVED** [review]

**Pull request merged**
