### PR TITLE
docs: add doc for is_strict_mode flag in HttpOptions

### PR DESCRIPTION
**Pull request by irenjj**
## What's Changed in this PR

add doc for is_strict_mode flag in HttpOptions

## Checklist

- [x] Please ensure that the content in `summary.yml` matches the current document structure when you changed the document structure.
- [ ] This change requires follow-up update in localized docs.

### CODE REVIEW

**Comment by tisonkun** [comment]
Thank you!

For cross reference, this is for https://github.com/GreptimeTeam/greptimedb/pull/3638#issuecomment-2051840260.

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]
master patch is merged.

What I'm concerned is that if we'll have a 0.7.3 release for these changes. Or if we'd release 0.8.0 directly, we may not add this to 0.7 branch ...

**Comment by nicecui** [comment]
> master patch is merged.
> 
> What I'm concerned is that if we'll have a 0.7.3 release for these changes. Or if we'd release 0.8.0 directly, we may not add this to 0.7 branch ...

Thanks to @irenjj for this contribution!
@tisonkun I will confirm the version question in the next week.

**Comment by nicecui** [comment]
Sorry for the late reply, we have added a nightly doc dictionary at `docs/nightly`, which is used for the v0.8 docs.

Could you please merge the main branch, and move the content in this PR to [`docs/nightly/en/user-guide/operations/configuration.md`](https://github.com/GreptimeTeam/docs/blob/main/docs/nightly/en/user-guide/operations/configuration.md) and [`docs/nightly/zh/user-guide/operations/configuration.md`](https://github.com/GreptimeTeam/docs/blob/main/docs/nightly/zh/user-guide/operations/configuration.md)?

Thank you very much!

**Pull request merged**
